/**
 * @param {String} campaign_email_id
 * @param {String} campaign_title
 * @param {String} campaign_updated_date
 * @param {String} campaign_updated_time
 */
module.exports = {
    started: {
        user_Template_subject: 'Campaign started.',
        body: '<!DOCTYPE html><html><head> <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"></head><body style="color: #000; font-family: -apple-system, BlinkMacSystemFont, \'Segoe UI\', Helvetica, Arial, sans-serif, \'Apple Color Emoji\', \'Segoe UI Emoji\', \'Segoe UI Symbol\'; line-height: 18px"> <style type="text/css"> body { color: #000; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"; line-height: 18px; } </style> <div style="margin: 0 auto; max-width: 600px; padding: 30px 0"> <table border="0" cellpadding="0" cellspacing="0" width="100%"> <tr> <td class="newsletter-header" style="text-align: center" align="center"> <div style="color: #333; display: block; margin-bottom: 10px; font-size: 24px; font-weight: bold">Email Scheduler</div> </td> </tr> <tr> <td class="newsletter-vertical-space" height="30" style="font-size: 0; line-height: 0"> </td> </tr> <tr> <td border="1" bordercolor="#e8e8e8" class="newsletter-hero" style="border: 1px solid #e8e8e8; border-radius: 5px 5px 5px 5px"> <table cellpadding="0" cellspacing="0" width="100%"> <tr> <td class="newsletter-hero--text" style="color: #534540; font-size: 18px; line-height: 26px; padding: 30px 20px"> <span>Hey {{:firstname}},<br> <br> We are thrilled to share this with you that your new campaign just went live. <br><br> It's time to wait for your prospect to respond because we can't wait for you to start closing these prospects.<br><br> If you got any questions or help more suggestions then feel free to reply to this email. </span> </td> </tr> <tr> <td style="color: #534540; font-size: 16px; line-height: 24px; padding: 20px"> <span> <i>Regards,</i><br> <i>Email Scheduler Team</i> </span> </td> </tr> </table> </td> </tr> </table> </div> <br /></body></html>'
    },
    completed: {
        user_Template_subject: 'Campaign completed.',
        body: '<!DOCTYPE html><html><head> <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"></head><body style="color: #000; font-family: -apple-system, BlinkMacSystemFont, \'Segoe UI\', Helvetica, Arial, sans-serif, \'Apple Color Emoji\', \'Segoe UI Emoji\', \'Segoe UI Symbol\'; line-height: 18px"> <style type="text/css"> body { color: #000; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"; line-height: 18px; } </style> <div style="margin: 0 auto; max-width: 600px; padding: 30px 0"> <table border="0" cellpadding="0" cellspacing="0" width="100%"> <tr> <td class="newsletter-header" style="text-align: center" align="center"> <div style="color: #333; display: block; margin-bottom: 10px; font-size: 24px; font-weight: bold">Email Scheduler</div> </td> </tr> <tr> <td class="newsletter-vertical-space" height="30" style="font-size: 0; line-height: 0"> </td> </tr> <tr> <td border="1" bordercolor="#e8e8e8" class="newsletter-hero" style="border: 1px solid #e8e8e8; border-radius: 5px 5px 5px 5px"> <table cellpadding="0" cellspacing="0" width="100%"> <tr> <td class="newsletter-hero--text" style="color: #534540; font-size: 18px; line-height: 26px; padding: 30px 20px"> <span>Hey {{:firstname}},<br> <br> We have just finished sending out emails to everyone for your campaign: {{:campaign_name}}. <br><br> Time to launch more campaigns. <br><br> If you got any questions or help more suggestions then feel free to reply to this email. </span> </td> </tr> <tr> <td style="color: #534540; font-size: 16px; line-height: 24px; padding: 20px"> <span> <i>Regards,</i><br> <i>Email Scheduler Team</i> </span> </td> </tr> </table> </td> </tr> </table> </div> <br /></body></html>'
    },
    rescheduledDueToApi: {
        user_Template_subject: 'Campaign rescheduled due to Rate Limiting.',
        body:
      '<!DOCTYPE html><html><head> <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"></head><body style="color: #000; font-family: -apple-system, BlinkMacSystemFont, \'Segoe UI\', Helvetica, Arial, sans-serif, \'Apple Color Emoji\', \'Segoe UI Emoji\', \'Segoe UI Symbol\'; line-height: 18px"> <style type="text/css"> body { color: #000; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"; line-height: 18px; } </style> <div style="margin: 0 auto; max-width: 600px; padding: 30px 0"> <table border="0" cellpadding="0" cellspacing="0" width="100%"> <tr> <td class="newsletter-header" style="text-align: center" align="center"> <div style="color: #333; display: block; margin-bottom: 10px; font-size: 24px; font-weight: bold">Email Scheduler</div> </td> </tr> <tr> <td class="newsletter-vertical-space" height="30" style="font-size: 0; line-height: 0"> </td> </tr> <tr> <td border="1" bordercolor="#e8e8e8" class="newsletter-hero" style="border: 1px solid #e8e8e8; border-radius: 5px 5px 5px 5px"> <table cellpadding="0" cellspacing="0" width="100%"> <tr> <td class="newsletter-hero--text" style="color: #534540; font-size: 18px; line-height: 26px; padding: 30px 20px"> <span>Hey {{:firstname}},<br> <br> It looks like something went wrong with your campaign: {{:campaign_name}}. <br><br> While sending out emails, your provider had blocked the emails. <br><br> This generally happens when you have reached your daily sending limit with your provider or they have blocked you. <br><br> <b style="color: black">However, we are here to help.</b> <br><br> We have automatically re-scheduled the emails for you. (We will make a total of 3 re-attempts) <br><br> If you got any questions or help more suggestions then feel free to reply to this email. </span> </td> </tr> <tr> <td style="color: #534540; font-size: 16px; line-height: 24px; padding: 20px"> <span> <i>Regards,</i><br> <i>Email Scheduler Team</i> </span> </td> </tr> </table> </td> </tr> </table> </div> <br /></body></html>'
    },
    rescheduledDueToOtherReasons: {
        user_Template_subject: 'Campaign rescheduled due to unknown reasons.',
        body:
      '<!DOCTYPE html><html><head> <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"></head><body style="color: #000; font-family: -apple-system, BlinkMacSystemFont, \'Segoe UI\', Helvetica, Arial, sans-serif, \'Apple Color Emoji\', \'Segoe UI Emoji\', \'Segoe UI Symbol\'; line-height: 18px"> <style type="text/css"> body { color: #000; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"; line-height: 18px; } </style> <div style="margin: 0 auto; max-width: 600px; padding: 30px 0"> <table border="0" cellpadding="0" cellspacing="0" width="100%"> <tr> <td class="newsletter-header" style="text-align: center" align="center"> <div style="color: #333; display: block; margin-bottom: 10px; font-size: 24px; font-weight: bold">Email Scheduler</div> </td> </tr> <tr> <td class="newsletter-vertical-space" height="30" style="font-size: 0; line-height: 0"> </td> </tr> <tr> <td border="1" bordercolor="#e8e8e8" class="newsletter-hero" style="border: 1px solid #e8e8e8; border-radius: 5px 5px 5px 5px"> <table cellpadding="0" cellspacing="0" width="100%"> <tr> <td class="newsletter-hero--text" style="color: #534540; font-size: 18px; line-height: 26px; padding: 30px 20px"> <span>Hey {{:firstname}},<br> <br> It looks like something went wrong with your campaign: {{:campaign_name}}. <br><br> While sending out emails, your provider had blocked the emails. <br><br> This generally happens when you have reached your daily sending limit with your provider or they have blocked you. <br><br> <b style="color: black">However, we are here to help.</b> <br><br> We have automatically re-scheduled the emails for you. (We will make a total of 3 re-attempts) <br><br> If you got any questions or help more suggestions then feel free to reply to this email. </span> </td> </tr> <tr> <td style="color: #534540; font-size: 16px; line-height: 24px; padding: 20px"> <span> <i>Regards,</i><br> <i>Email Scheduler Team</i> </span> </td> </tr> </table> </td> </tr> </table> </div> <br /></body></html>'
    }
};
